vegancity/urls.py
# Copyright (C) 2012 Steve Lamb

# This file is part of Vegancity.

# Vegancity is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Vegancity is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Vegancity.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url
from django.contrib import admin
from vegancity import views
from .api import build_api

admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^api/', include(build_api().urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/pending_approval/$', 'vegancity.admin_views.pending_approval', name="pending_approval"),
    url(r'^admin/pending_approval/count/$', 'vegancity.admin_views.pending_approval_count', name="pending_approval_count"),
    url(r'^admin/mailing_list/$', 'vegancity.admin_views.mailing_list', name="mailing_list"),
    url(r'^admin/vendor_list/$', 'vegancity.admin_views.vendor_list', name="vendor_list"),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', views.home, name='home'),
    url(r'^vendors/$', views.vendors, name="vendors"),
    url(r'^vendors/add/$', views.new_vendor, name="new_vendor"),
    url(r'^vendors/add/thanks/$', views.VendorThanksView.as_view(), name="vendor_thanks"),
    url(r'^vendors/review/(?P<vendor_id>\d+)/$', views.new_review, name="new_review"),
    url(r'^vendors/(?P<pk>\d+)(-[\w\d]+)*/$', views.vendor_detail, name="vendor_detail"),
    url(r'^connect/$', views.ConnectView.as_view(), name='connect'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^privacy/$', views.PrivacyView.as_view(), name='privacy'),
    url(r'^vendors/review/(?P<pk>\d+)/thanks/$', views.ReviewThanksView.as_view(), name="review_thanks"),

    url(r'^accounts/login/$',  'django.contrib.auth.views.login', name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'},  name='logout'),
    url(r'^accounts/register/$', 'vegancity.views.register', name='register'),
    url(r'^accounts/register/thanks/$', views.RegisterThanksView.as_view(), name='register_thanks'),
    url(r'^accounts/password/change/$', 'vegancity.views.password_change', name='password_change'),
    url(r'^accounts/password/reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^accounts/password/reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'),
    url(r'^accounts/password/reset/complete/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),
    url(r'^accounts/profile/$', 'vegancity.views.user_profile', {'username': None}, name='my_account'),
    url(r'^accounts/profile/edit/$', 'vegancity.views.account_edit', name='account_edit'),

    url(r'^users/(?P<username>[a-zA-Z0-9_@.+-]+)/$', 'vegancity.views.user_profile', name='user_profile'),
)

vegancity/models.py
# Copyright (C) 2012 Steve Lamb

# This file is part of Vegancity.

# Vegancity is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Vegancity is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Vegancity.  If not, see <http://www.gnu.org/licenses/>.

from django.contrib.gis.db import models
from django.contrib.gis.geos import Point
from django.contrib.auth.models import User

from django.db.models.signals import m2m_changed

from django.db.models import Count

from django.template.defaultfilters import slugify
from django.core.exceptions import ValidationError, ObjectDoesNotExist

import collections
import logging
import random

from vegancity import geocode, validators, email

from djorm_pgfulltext.models import SearchManagerMixIn
from djorm_pgfulltext.fields import VectorField

logger = logging.getLogger(__name__)


class VendorSearchManagerMixin(SearchManagerMixIn):
    def vendor_search(self, *args, **kwargs):
        qs = self.search(*args, **kwargs).values_list('vendor', flat=True)
        # TODO: not sure why this has to be casted to a list, but
        # caused an error without it
        vendors = Vendor.approved_objects.filter(pk__in=list(qs))
        return vendors


class WithVendorsManagerMixin(object):
    """
    Adds a method for conveniently filtering down to only
    objects with approved vendors.
    """
    def with_vendors(self, vendors=None):
        qs = self.filter(vendor__approval_status='approved')

        if not (vendors is None):
            qs = qs.filter(vendor__in=vendors)

        qs = (qs
              .distinct()
              .annotate(vendor_count=Count('vendor'))
              .filter(vendor_count__gt=0)
              .order_by('-vendor_count'))

        return qs


class VendorSearchManager(VendorSearchManagerMixin, models.Manager):
    pass


class WithVendorsManager(WithVendorsManagerMixin,
                         models.Manager):
    pass


class TagManager(WithVendorsManagerMixin,
                 VendorSearchManagerMixin,
                 models.Manager):
    pass


class _TagModel(models.Model):

    name = models.CharField(
        help_text="short name, all lowercase alphas, underscores for spaces",
        max_length=255, unique=True
    )
    description = models.CharField(
        help_text="Nicely formatted text.  About a sentence.",
        max_length=255
    )
    created = models.DateTimeField(auto_now_add=True, null=True)

    def __unicode__(self):
        return self.description

    class Meta:
        abstract = True
        get_latest_by = "created"
        ordering = ('name',)

#######################################
# SITE CLASSES
#######################################


class VegLevel(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    super_category = models.CharField(max_length=30,
                                      choices=(
                                          ('vegan', 'Vegan'),
                                          ('vegetarian', 'Vegetarian'),
                                          ('not_veg', 'Not Vegetarian')))

    def __unicode__(self):
        return "(%s) %s" % (self.super_category, self.description)


class Neighborhood(models.Model):

    """Used for determining what neighborhood a vendor is in."""
    name = models.CharField(max_length=255, unique=True)
    created = models.DateTimeField(auto_now_add=True, null=True)

    objects = WithVendorsManager()

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = "Neighborhood"
        verbose_name_plural = "Neighborhoods"
        get_latest_by = "created"
        ordering = ('name',)


##########################################
# USER-RELATED MODELS
##########################################

class UserProfile(models.Model):
    user = models.ForeignKey(User, unique=True)
    mailing_list = models.BooleanField(default=False)
    karma_points = models.IntegerField(null=True, blank=True)
    bio = models.TextField(null=True, blank=True)

##########################################
# VENDOR-RELATED MODELS
##########################################


class VeganDish(models.Model):
    name = models.CharField(max_length=255, unique=True)
    created = models.DateTimeField(auto_now_add=True, null=True)

    search_index = VectorField()

    objects = VendorSearchManager(
        fields=('name'),
        auto_update_search_field=True
    )

    def __unicode__(self):
        return self.name

    class Meta:
        get_latest_by = "created"
        ordering = ('name',)
        verbose_name = "Vegan Dish"
        verbose_name_plural = "Vegan Dishes"


class ReviewManager(VendorSearchManagerMixin, models.Manager):

    "Manager class for handling searches by review."

    def pending_approval(self):
        """returns all reviews that are not approved, which are
        otherwise impossible to get in a normal query (for now)."""
        normal_qs = self.get_query_set()
        pending = normal_qs.filter(approved=False)
        return pending


class ApprovedReviewManager(ReviewManager):

    "Manager for approved reviews only."

    def get_query_set(self):
        "Changing initial queryset to ignore approved."
        normal_qs = super(ApprovedReviewManager, self).get_query_set()
        new_qs = normal_qs.filter(approved=True)
        return new_qs


class Review(models.Model):

    # CORE FIELDS
    vendor = models.ForeignKey('Vendor')
    author = models.ForeignKey(User)

    # ADMINISTRATIVE FIELDS
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=False, db_index=True)
    search_index = VectorField()

    objects = ReviewManager(
        fields=('title', 'content'),
        auto_update_search_field = True
    )
    approved_objects = ApprovedReviewManager(
        fields=('title', 'content'),
        auto_update_search_field = True
    )

    # DESCRIPTIVE FIELDS
    title = models.CharField(
        "Title of review (optional)",
        max_length=255, null=True, blank=True)
    food_rating = models.IntegerField(
        "How would you rate the food, overall?",
        choices=tuple((i, i) for i in range(1, 5)),
        blank=True, null=True,)
    atmosphere_rating = models.IntegerField(
        "How would you rate the atmosphere?",
        choices=tuple((i, i) for i in range(1, 5)),
        blank=True, null=True,)
    best_vegan_dish = models.ForeignKey(
        'VeganDish',
        verbose_name="Favorite Vegan Dish",
        blank=True, null=True)
    unlisted_vegan_dish = models.CharField(max_length=100,
                                           blank=True, null=True)
    suggested_feature_tags = models.CharField(max_length=255,
                                              blank=True, null=True)
    suggested_cuisine_tags = models.CharField(max_length=255,
                                              blank=True, null=True)
    content = models.TextField("Review")

    def __unicode__(self):
        return "%s -- %s" % (self.vendor.name, str(self.created))

    def get_absolute_url(self):
        return "/vendors/%d-%s/" % (self.vendor.id, slugify(self.vendor.name))

    class Meta:
        get_latest_by = "created"
        ordering = ('created',)
        verbose_name = "Review"
        verbose_name_plural = "Reviews"


class VendorManager(SearchManagerMixIn, models.GeoManager):

    "Manager class for handling searches by vendor."

    def pending_approval(self):
        """returns all vendors that are not approved, which are
        otherwise impossible to get in a normal query."""
        return self.filter(approval_status='pending')


class ApprovedVendorManager(VendorManager):

    """Manager for approved vendors only.

    Inherits the normal vendor manager."""

    def get_query_set(self):
        normal_qs = super(VendorManager, self).get_query_set()
        new_qs = normal_qs.filter(approval_status='approved')
        return new_qs

    def without_reviews(self):
        review_vendors = (Review
                          .approved_objects
                          .values_list('vendor_id', flat=True))
        return self.all().exclude(pk__in=review_vendors)

    def with_reviews(self):
        return self.filter(review__approved=True)\
                   .distinct()\
                   .annotate(review_count=Count('review'))\
                   .order_by('-review_count')

    def get_random_unreviewed(self):
        try:
            return random.choice(self.without_reviews())
        except IndexError:
            return None


class Vendor(models.Model):

    "The main class for this application"

    # CORE FIELDS
    name = models.CharField(max_length=255, unique=True, db_index=True)
    address = models.TextField(null=True)
    neighborhood = models.ForeignKey('Neighborhood', blank=True, null=True,
                                     db_index=True)
    phone = models.CharField(max_length=50, blank=True, null=True,
                             validators=[validators.validate_phone_number])
    website = models.URLField(blank=True, null=True,
                              validators=[validators.validate_website])
    location = models.PointField(srid=4326, default=None,
                                 null=True, blank=True, editable=False)

    # ADMINISTRATIVE FIELDS
    created = models.DateTimeField(auto_now_add=True, null=True)
    submitted_by = models.ForeignKey(User, null=True, blank=True)

templates/vegancity/about.html
{% extends "base_page.html" %}

{% block title %}VegPhilly | About{% endblock %}

{% block header_extra %}
<meta name="description" content="Read the story behind VegPhilly, meet the founders and contributors, and see the free software tools used to make the site.">
{% endblock header_extra %}

{% block content %}
<div class="container">
  <div class="about-hero row">
    <h3>VegPhilly helps answer the inevitable question:</h3>
    <h2>Where are we going to eat?<h2>
    </div>

    <div class="about-summary row">
      <div class="span4">
        <p>We founded VegPhilly because we wanted more detailed and accurate information about vegan and vegan-friendly establishments in our city. We want to create the most comprehensive list of vegan restaurants and places that offer vegan options, reviewed and rated.</p>
      </div>
      <div class="span4">
        <p>We need your help to make the site better. After creating an account, you can add new restaurants, write reviews, and even add your favorite vegan dishes. Please contact us at <a href="mailto:vegphilly@gmail.com">vegphilly@gmail.com</a> if you have any comments, questions, or suggestions.</p>
      </div>
      <div class="span4">
        <p>VegPhilly is built with free and open source software. Our vision is to produce a framework for a vegan website that is easily deployable in any city. If you are interested in using our code to start a site in your city, contact us or check out our source code on <a href="http://github.com/steventlamb/django-vegancity" target="_blank">Github</a>.</p>
      </div>

    </div>

    <br>
    <br>
    <i class="icon-long-arrow-right"></i>
    <h3>Team</h3>
    <div class="row bios" style="text-align: center">
      <div class="span4 team-member">
        <img class="aboutpic" src="{{ STATIC_URL }}images/steveV2.jpg">
        <h5>Steve Lamb</h5>
        <h6>Software Engineering</h6>
        <a href="https://twitter.com/steventlamb" target="_blank">@steventlamb</a>
      </div>
      <div class="span4 team-member">
        <img class="aboutpic" src="{{ STATIC_URL }}images/jonathancropped.jpg">
        <h5>Jonathan Farbowitz</h5>
        <h6>Content & QA</h6>
      </div>
      <div class="span4 team-member">
        <img class="aboutpic" src="{{ STATIC_URL }}images/zack.jpg">
        <h5>Zack Birmingham</h5>
        <h6>Design</h6>
        <a href="https://twitter.com/bruce_e_kinesis" target="_blank">@bruce_e_kinesis</a>
      </div>
    </div>
    <div class="row bios" style="text-align: center">
      <div class="span4 team-member">
        <img class="aboutpic" src="{{ STATIC_URL }}images/alexandraV2.jpg">
        <h5>Alexandra Hoefinger</h5>
        <h6>Front End Development</h6>
        <a href="https://twitter.com/ahoefinger" target="_blank">@ahoefinger</a>
      </div>

      <div class="span4 team-member">
        <img class="aboutpic" src="{{ STATIC_URL }}images/chris.jpg">
        <h5>Christopher Wimbrow</h5>
        <h6>Software Engineering</h6>
        <a href="https://twitter.com/christopher_eye" target="_blank">@christopher_eye</a>
      </div>
      <div class="span4 team-member">
        <img class="aboutpic" src="{{ STATIC_URL }}images/kim.jpg">
        <h5>Kim Showell</h5>
        <h6>Social Media</h6>
        <a href="https://twitter.com/kayelless13" target="_blank">@kayelless13</a>
      </div>
    </div>
    <hr>
    <i class="icon-long-arrow-right"></i>

    <div class="row bios" >
      <div class="span6">
        <h3>Contributors</h3>
        <div class="contributors">
          <h5>Jeff Frankl</h5>
          <h5>Jeremie Rose Wimbrow</h5>
          <br>
          <h5><a href="mailto:vegphilly@gmail.com">Email us</a> to share ideas and get involved!</h5>
          <br>
          <br>
        </div>
      </div>
      <div class="span6" >
        <div class="badge-container">
          <img class="be-well-badge" src="{{ STATIC_URL }}images/be-well-badge.png">
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block body_extra %}
<link href='http://fonts.googleapis.com/css?family=Chivo:400,400italic' rel='stylesheet' type='text/css'>

<style>
.about-hero
{
  background-image:url('{{ STATIC_URL }}images/skyline.png');
}
</style>

<link rel="stylesheet" href="{{ STATIC_URL }}css/about_page.css">

{% endblock body_extra %}

templates/vegancity/approval_email.html
<html>
<h1>Submission Approved!</h1>

<p>Thanks for adding {{ vendor.name }} to VegPhilly. Your submission has been approved.</p>

<p>While you're at it, why not write a <a href="www.vegphilly.com/{{ vendor.get_absolute_url }}">review</a>?</p>

<a href="http://twitter.com/intent/tweet?url=http://www.vegphilly.com{{ vendor.get_absolute_url }}&text=I just added {{ vendor.name }} to VegPhilly!&via=vegphilly" target="_blank">Click here to tweet about this!</a>

<p>
Thanks,<br>
The VegPhilly Team
</p>

</html>

templates/vegancity/blog.html
{% extends "base_page.html" %}

{% block title %}VegPhilly | Blog{% endblock %}

{% block header_extra %}
  <meta name="description" content="Read blog posts about the latest VegPhilly news and local vegan and vegetarian restaurant information.">
{% endblock header_extra %}

{% block headline %}Welcome to the VegPhilly Blog!{% endblock %}

{% block summary %}
{% endblock %}

{% block content %}
  <div class="container">
  <div class="row">
    <div class="span6">
      {% if object_list %}
        {{ object_list.count }} entries.
        <hr/>
        {% for entry in object_list %}
          <h5>{{ entry.title }}</h5>
          <h6>by {{ entry.author }}&nbsp;{{ entry.created }}</h6>
      <p>{{ entry.body|safe }}</p>
      <hr/>
    {% endfor %}
  {% else %}
    <h4>no blog entries.</h4>  
  {% endif %}
    </div>
    <div class="span6 hidden-phone">
      <img src="{{ STATIC_URL }}images/fat-cat-frame-mockup.png" class="cat" alt="VegPhilly's mascot illustration" width="325px">
      <div id="caption"> <p>Mr. Peppers, VegPhilly's original spokescat<p> </div>
    </div>
  </div>
  </div>

{% endblock content %}

{% block body_extra %}

  <style>

  .cat {
    box-shadow: 5px 5px 5px #888;
    display: block;
    margin: auto;
    margin-top: 125px;
  }

  #caption {
    text-align: center;
    margin-top: 20px;
  }

  </style>

{% endblock body_extra %}

templates/vegancity/carousel.html
<!-- styles and markup for flyer carousel -->

{% extends "base_page.html" %}

{% block title %}{% endblock %}

{% block headline %}{% endblock %}

{% block content %}
<div class="container">
<h3>Check Out Our Flyers!</h3>
  <br>
  <p>Browse through the gallery below to see our designs, or <a href="#">download and print a sheet of four</a>. If you have ideas for a flyer, we'd love to include your designs here too. <a href="mailto:vegphilly@gmail.com">Let's talk!</a></p>
  <p>
  <br>
  <div id="this-carousel-id" class="carousel slide"></div>
</div>
{% endblock content %}

{% block body_extra %}

<script>
  $(document).ready(function(){
    $('.carousel').carousel();
  });
</script>

<style type="text/css">

.carousel {
  width: 55%;
  min-width: 400px;
  margin: 0 auto;
}

.carousel-item {
  margin: 0 auto;
}

</style>
{% endblock body_extra %}

templates/vegancity/connect.html
{% extends "base_page.html" %}

{% block title %}VegPhilly | Connect{% endblock title %}

{% block headline %}Connect{% endblock headline %}

{% block content %}
<iframe src="https://www.google.com/calendar/embed?mode=AGENDA&height=600&wkst=1&bgcolor=%23FFFFFF&src=vegphilly%40gmail.com&color=%232F6309&ctz=America%2FNew_York" 
	style=" border-width:0 " width="800" height="600" frameborder="0" scrolling="no"></iframe>
{% endblock content %}

templates/vegancity/new_review.html
{% extends "base_page.html" %}

{% load url from future %}

{% block headline %}Write a Review{% endblock %}

{% block content %}
<div class="container">

<h3>{{ vendor.name }}</h3>
<form action="" method="post">
  {% csrf_token %}
  {{ form.vendor }}

  {% if form.errors %}
    <span style="color: red">
      <p>There were errors in your submission. Please review the information below.</p>
      {{ form.errors }}
    </span>

  {% endif %} 

  <div class="row">
    <div class="span6">
      <div class="fieldWrapper">
        <span style="color: red">{{ form.title.errors }}</span>
        {{ form.title.label_tag }}
        {{ form.title }}
        {{ form.title.help_text }}
      </div>

      <div class="fieldWrapper">
        <span style="color: red">{{ form.food_rating.errors }}</span>
        {{ form.food_rating.label_tag }}
        {{ form.food_rating }}
        {{ form.food_rating.help_text }}
      </div>

      <div class="fieldWrapper">
        <span style="color: red">{{ form.atmosphere_rating.errors }}</span>
        {{ form.atmosphere_rating.label_tag }}
        {{ form.atmosphere_rating }}
        {{ form.atmosphere_rating.help_text }}
      </div>

      <div class="fieldWrapper vegan-dish-choices">
        <span style="color: red">{{ form.best_vegan_dish.errors }}</span>
        {{ form.best_vegan_dish.label_tag }}
        {{ form.best_vegan_dish }}
        {{ form.best_vegan_dish.help_text }}
      </div>
      
      <div class="fieldWrapper vegan-dish-freeform">
        <span style="color: red">{{ form.unlisted_vegan_dish.errors }}</span>
        <label for="id_unlisted_vegan_dish">Favorite Vegan Dish <span class="if-unlisted">(if unlisted)</span></label>
        {{ form.unlisted_vegan_dish }}
        {{ form.unlisted_vegan_dish.help_text }}
      </div>

      <div class="fieldWrapper">
        <span style="color: red">{{ form.suggested_feature_tags.errors }}</span>
        {{ form.suggested_feature_tags.label_tag }}
        {{ form.suggested_feature_tags }}
        {{ form.suggested_feature_tags.help_text }}
      </div>

      <div class="fieldWrapper">
        <span style="color: red">{{ form.suggested_cuisine_tags.errors }}</span>
        {{ form.suggested_cuisine_tags.label_tag }}
        {{ form.suggested_cuisine_tags }}
        {{ form.suggested_cuisine_tags.help_text }}
      </div>

      <div class="fieldWrapper">
        <span style="color: red">{{ form.content.errors }}</span>
        {{ form.content.label_tag }}
        {{ form.content }}
        {{ form.content.help_text }}
      </div>

      <input type="submit" class="btn btn-custom" value="Submit" id="id_submit">
    </div> <!-- span6 -->

    <div class="span6 visible-desktop">
      <p>If the vegan dish you'd like to review is not available from the dropdown, please enter it in the textbox and we'll add it to the site so others can select it.</p>

      </p>Please note that all reviews will be moderated by an admin. Negative reviews are welcome, but they will be scrutinized for slander. No trolling!</p>

      <br><br>
      <br><br>
      <br><br>
      <br><br>
      <h3>{{ vendor.name }}</h3>

      <h6>Current Cuisine Tags:</h6><p>{% for tag in vendor.cuisine_tags.all %}{{ tag }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

      <h6>Current Feature Tags:</h6><p>{% for tag in vendor.feature_tags.all %}{{ tag }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

      <a target="_BLANK" href="{% url 'vendor_detail' pk=vendor.id %}">more...</a>

    </div> <!-- span6 -->
  </div> <!-- row -->

</form>
</div>
{% endblock content %}

{% block body_extra %}
<script type="text/javascript" src="{{ STATIC_URL }}js/review_form.js"></script>
{% endblock body_extra %}

templates/vegancity/new_vendor.html
{% extends "base_page.html" %}

{% block headline %}Add a Food Vendor{% endblock %}

{% block content %}
  <div class="container">

  <form action="" method="post">
    {{ form.non_field_errors }}
    {% if form.errors %}
      <p style="color: red">There were errors in your submission. Please review the fields below.</p>
      <br>
    {% endif %} 
    {% csrf_token %}

    <div class="row">
      <div class="span4">
        <div class="fieldWrapper">
          {% with errors=form.name.errors %}
          <label for="id_name">{{ form.name.label }}
            {% if errors %}<span style="color: red">* (Required)</span>{% endif %}
          </label>
          {% if errors %}
          <div style="color: red">
            {{ errors }}
          </div>
          {% endif %}
          {{ form.name }}
          {% endwith %}
        </div>

        <div class="fieldWrapper">
          <label for="id_address">{{ form.address.label }}
            {% if form.address.errors %}<span style="color: red">* (Required)</span>{% endif %}
          </label>
          {{ form.address }}
        </div>

        <div class="fieldWrapper">
          {{ form.veg_level.errors }}
          {{ form.veg_level.label_tag }}
          {{ form.veg_level }}
        </div>

      </div>
      <div class="span4">

        <div class="fieldWrapper">
          {{ form.phone.errors }}
          {{ form.phone.label_tag }}
          {{ form.phone }}
        </div>


        <div class="fieldWrapper">
          {{ form.website.errors }}
          {{ form.website.label_tag }}
          {{ form.website }}
        </div>

        <div class="fieldWrapper">
          {{ form.notes.errors }}
          {{ form.notes.label_tag }}
          {{ form.notes }}<br>
          ({{ form.notes.help_text }})
        </div>

        <div class="span2"></div>
        <div class="span2"></div>
      </div>
    </div>

    <hr/>

    <div class="row">
      <div class="span4">
        <div class="fieldWrapper">
          {{ form.cuisine_tags.errors }}
          {{ form.cuisine_tags.label_tag }}
          {{ form.cuisine_tags }}
        </div>
      </div>
      <div class="span4">
        <div class="fieldWrapper">
          {{ form.feature_tags.errors }}
          {{ form.feature_tags.label_tag }}
          {{ form.feature_tags }}
        </div>
      </div>
      <div class="span2"></div>
      <div class="span2"></div>

    </div>
    <hr/>
    <input type="submit" class="btn btn-custom" value="Submit">

  </form>
  </div>

{% endblock content %}


{% block body_extra %}
  <script type="text/javascript" src="{{ STATIC_URL }}js/vendor_form.js"></script>
{% endblock body_extra %}

templates/vegancity/register.html
{% extends "base_page.html" %}

{% block headline %}Register{% endblock %}

{% block content %}
<div class="container">

<br>
<p>Please take note of our <a class="uline" href="#privacyModal" data-toggle="modal">Privacy Policy</a></p>
{% include "vegancity/partials/privacy_modal.html" %}
<hr>
  <form action="" method="post">
    {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-custom" type="submit" value="Create">
  </form>

</div>
{% endblock content %}

templates/vegancity/register_thanks.html
{% extends "vegancity/thanks.html" %}

{% load url from future %}

{% block action %}
  Thanks for creating an account!
{% endblock %}

{% block initial_thanks %}
  We hope you enjoy VegPhilly.<br/><br/>
  If you have any questions, concerns, or suggestions please contact us at 
  <a href="mailto:vegphilly@gmail.com">vegphilly@gmail.com</a>.
{% endblock %}

templates/vegancity/review.html
{% extends "base.html" %}

{% block headline %}Write a review!{% endblock %}

{% block content %}
<h3>{{ vendor.name }}</h3>
  <form action="" method="post">
    {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit">
  </form>
{% endblock %}