vegancity/urls.py
# Copyright (C) 2012 Steve Lamb

# This file is part of Vegancity.

# Vegancity is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Vegancity is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Vegancity.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url
from django.contrib import admin
from vegancity import views
from .api import build_api

admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^api/', include(build_api().urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/pending_approval/$', 'vegancity.admin_views.pending_approval', name="pending_approval"),
    url(r'^admin/pending_approval/count/$', 'vegancity.admin_views.pending_approval_count', name="pending_approval_count"),
    url(r'^admin/mailing_list/$', 'vegancity.admin_views.mailing_list', name="mailing_list"),
    url(r'^admin/vendor_list/$', 'vegancity.admin_views.vendor_list', name="vendor_list"),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', views.home, name='home'),
    url(r'^vendors/$', views.vendors, name="vendors"),
    url(r'^vendors/add/$', views.new_vendor, name="new_vendor"),
    url(r'^vendors/add/thanks/$', views.VendorThanksView.as_view(), name="vendor_thanks"),
    url(r'^vendors/review/(?P<vendor_id>\d+)/$', views.new_review, name="new_review"),
    url(r'^vendors/(?P<pk>\d+)(-[\w\d]+)*/$', views.vendor_detail, name="vendor_detail"),
    url(r'^connect/$', views.ConnectView.as_view(), name='connect'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^privacy/$', views.PrivacyView.as_view(), name='privacy'),
    url(r'^vendors/review/(?P<pk>\d+)/thanks/$', views.ReviewThanksView.as_view(), name="review_thanks"),

    url(r'^accounts/login/$',  'django.contrib.auth.views.login', name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'},  name='logout'),
    url(r'^accounts/register/$', 'vegancity.views.register', name='register'),
    url(r'^accounts/register/thanks/$', views.RegisterThanksView.as_view(), name='register_thanks'),
    url(r'^accounts/password/change/$', 'vegancity.views.password_change', name='password_change'),
    url(r'^accounts/password/reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^accounts/password/reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'),
    url(r'^accounts/password/reset/complete/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),
    url(r'^accounts/profile/$', 'vegancity.views.user_profile', {'username': None}, name='my_account'),
    url(r'^accounts/profile/edit/$', 'vegancity.views.account_edit', name='account_edit'),

    url(r'^users/(?P<username>[a-zA-Z0-9_@.+-]+)/$', 'vegancity.views.user_profile', name='user_profile'),
)

vegancity/models.py
# Copyright (C) 2012 Steve Lamb

# This file is part of Vegancity.

# Vegancity is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Vegancity is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Vegancity.  If not, see <http://www.gnu.org/licenses/>.

from django.contrib.gis.db import models
from django.contrib.gis.geos import Point
from django.contrib.auth.models import User

from django.db.models.signals import m2m_changed

from django.db.models import Count

from django.template.defaultfilters import slugify
from django.core.exceptions import ValidationError, ObjectDoesNotExist

import collections
import logging
import random

from vegancity import geocode, validators, email

from djorm_pgfulltext.models import SearchManagerMixIn
from djorm_pgfulltext.fields import VectorField

logger = logging.getLogger(__name__)


class VendorSearchManagerMixin(SearchManagerMixIn):
    def vendor_search(self, *args, **kwargs):
        qs = self.search(*args, **kwargs).values_list('vendor', flat=True)
        # TODO: not sure why this has to be casted to a list, but
        # caused an error without it
        vendors = Vendor.approved_objects.filter(pk__in=list(qs))
        return vendors


class WithVendorsManagerMixin(object):
    """
    Adds a method for conveniently filtering down to only
    objects with approved vendors.
    """
    def with_vendors(self, vendors=None):
        qs = self.filter(vendor__approval_status='approved')

        if not (vendors is None):
            qs = qs.filter(vendor__in=vendors)

        qs = (qs
              .distinct()
              .annotate(vendor_count=Count('vendor'))
              .filter(vendor_count__gt=0)
              .order_by('-vendor_count'))

        return qs


class VendorSearchManager(VendorSearchManagerMixin, models.Manager):
    pass


class WithVendorsManager(WithVendorsManagerMixin,
                         models.Manager):
    pass


class TagManager(WithVendorsManagerMixin,
                 VendorSearchManagerMixin,
                 models.Manager):
    pass


class _TagModel(models.Model):

    name = models.CharField(
        help_text="short name, all lowercase alphas, underscores for spaces",
        max_length=255, unique=True
    )
    description = models.CharField(
        help_text="Nicely formatted text.  About a sentence.",
        max_length=255
    )
    created = models.DateTimeField(auto_now_add=True, null=True)

    def __unicode__(self):
        return self.description

    class Meta:
        abstract = True
        get_latest_by = "created"
        ordering = ('name',)

#######################################
# SITE CLASSES
#######################################


class VegLevel(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    super_category = models.CharField(max_length=30,
                                      choices=(
                                          ('vegan', 'Vegan'),
                                          ('vegetarian', 'Vegetarian'),
                                          ('not_veg', 'Not Vegetarian')))

    def __unicode__(self):
        return "(%s) %s" % (self.super_category, self.description)


class Neighborhood(models.Model):

    """Used for determining what neighborhood a vendor is in."""
    name = models.CharField(max_length=255, unique=True)
    created = models.DateTimeField(auto_now_add=True, null=True)

    objects = WithVendorsManager()

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = "Neighborhood"
        verbose_name_plural = "Neighborhoods"
        get_latest_by = "created"
        ordering = ('name',)


##########################################
# USER-RELATED MODELS
##########################################

class UserProfile(models.Model):
    user = models.ForeignKey(User, unique=True)
    mailing_list = models.BooleanField(default=False)
    karma_points = models.IntegerField(null=True, blank=True)
    bio = models.TextField(null=True, blank=True)

##########################################
# VENDOR-RELATED MODELS
##########################################


class VeganDish(models.Model):
    name = models.CharField(max_length=255, unique=True)
    created = models.DateTimeField(auto_now_add=True, null=True)

    search_index = VectorField()

    objects = VendorSearchManager(
        fields=('name'),
        auto_update_search_field=True
    )

    def __unicode__(self):
        return self.name

    class Meta:
        get_latest_by = "created"
        ordering = ('name',)
        verbose_name = "Vegan Dish"
        verbose_name_plural = "Vegan Dishes"


class ReviewManager(VendorSearchManagerMixin, models.Manager):

    "Manager class for handling searches by review."

    def pending_approval(self):
        """returns all reviews that are not approved, which are
        otherwise impossible to get in a normal query (for now)."""
        normal_qs = self.get_query_set()
        pending = normal_qs.filter(approved=False)
        return pending


class ApprovedReviewManager(ReviewManager):

    "Manager for approved reviews only."

    def get_query_set(self):
        "Changing initial queryset to ignore approved."
        normal_qs = super(ApprovedReviewManager, self).get_query_set()
        new_qs = normal_qs.filter(approved=True)
        return new_qs


class Review(models.Model):

    # CORE FIELDS
    vendor = models.ForeignKey('Vendor')
    author = models.ForeignKey(User)

    # ADMINISTRATIVE FIELDS
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=False, db_index=True)
    search_index = VectorField()

    objects = ReviewManager(
        fields=('title', 'content'),
        auto_update_search_field = True
    )
    approved_objects = ApprovedReviewManager(
        fields=('title', 'content'),
        auto_update_search_field = True
    )

    # DESCRIPTIVE FIELDS
    title = models.CharField(
        "Title of review (optional)",
        max_length=255, null=True, blank=True)
    food_rating = models.IntegerField(
        "How would you rate the food, overall?",
        choices=tuple((i, i) for i in range(1, 5)),
        blank=True, null=True,)
    atmosphere_rating = models.IntegerField(
        "How would you rate the atmosphere?",
        choices=tuple((i, i) for i in range(1, 5)),
        blank=True, null=True,)
    best_vegan_dish = models.ForeignKey(
        'VeganDish',
        verbose_name="Favorite Vegan Dish",
        blank=True, null=True)
    unlisted_vegan_dish = models.CharField(max_length=100,
                                           blank=True, null=True)
    suggested_feature_tags = models.CharField(max_length=255,
                                              blank=True, null=True)
    suggested_cuisine_tags = models.CharField(max_length=255,
                                              blank=True, null=True)
    content = models.TextField("Review")

    def __unicode__(self):
        return "%s -- %s" % (self.vendor.name, str(self.created))

    def get_absolute_url(self):
        return "/vendors/%d-%s/" % (self.vendor.id, slugify(self.vendor.name))

    class Meta:
        get_latest_by = "created"
        ordering = ('created',)
        verbose_name = "Review"
        verbose_name_plural = "Reviews"


class VendorManager(SearchManagerMixIn, models.GeoManager):

    "Manager class for handling searches by vendor."

    def pending_approval(self):
        """returns all vendors that are not approved, which are
        otherwise impossible to get in a normal query."""
        return self.filter(approval_status='pending')


class ApprovedVendorManager(VendorManager):

    """Manager for approved vendors only.

    Inherits the normal vendor manager."""

    def get_query_set(self):
        normal_qs = super(VendorManager, self).get_query_set()
        new_qs = normal_qs.filter(approval_status='approved')
        return new_qs

    def without_reviews(self):
        review_vendors = (Review
                          .approved_objects
                          .values_list('vendor_id', flat=True))
        return self.all().exclude(pk__in=review_vendors)

    def with_reviews(self):
        return self.filter(review__approved=True)\
                   .distinct()\
                   .annotate(review_count=Count('review'))\
                   .order_by('-review_count')

    def get_random_unreviewed(self):
        try:
            return random.choice(self.without_reviews())
        except IndexError:
            return None


class Vendor(models.Model):

    "The main class for this application"

    # CORE FIELDS
    name = models.CharField(max_length=255, unique=True, db_index=True)
    address = models.TextField(null=True)
    neighborhood = models.ForeignKey('Neighborhood', blank=True, null=True,
                                     db_index=True)
    phone = models.CharField(max_length=50, blank=True, null=True,
                             validators=[validators.validate_phone_number])
    website = models.URLField(blank=True, null=True,
                              validators=[validators.validate_website])
    location = models.PointField(srid=4326, default=None,
                                 null=True, blank=True, editable=False)

    # ADMINISTRATIVE FIELDS
    created = models.DateTimeField(auto_now_add=True, null=True)
    submitted_by = models.ForeignKey(User, null=True, blank=True)

templates/vegancity/partials/footer.html
<div id="footer">
    <ul class="footer-links">
      <li><a href="{% url 'privacy' %}">Privacy Policy</a></li>
      <li><a href="{% url 'about' %}">About</a></li>
      <li><a href="http://www.facebook.com/vegphilly"><i class="fa fa-facebook"></i></a></li>
      <li><a href="http://www.twitter.com/vegphilly"><i class="fa fa-twitter"></i></a></li>
    </ul>
</div>

templates/vegancity/partials/navbar.html
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href= "{% url 'home' %}"><img src="{{ STATIC_URL }}images/vegphilly-carrot-logo.png" alt="VegPhilly carrot logo" width="24px"></a>
      <a class="brand" href= "{% url 'home' %}" style="color: white; padding-top: 35px">VegPhilly</a>

      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <i class="fa fa-bars"></i>
      </a>

      <div class="nav-collapse collapse">
        <ul class="nav pull-right">
	  <li><a href="{% url 'vendors' %}"><p class="vc-nav-item">Restaurants</p></a></li>
	  <li><a href="{% url 'connect' %}"><p class="vc-nav-item">Connect</p></a></li>
          <li><a href="{% url 'about' %}"><p class="vc-nav-item">About</p></a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'my_account' %}"><p class="vc-nav-item">My Account (<u>{{user}}</u>)</p></a></li>
          <li><a href="{% url 'logout' %}"><p class="vc-nav-item">Logout</p></a></li>
          {% else %}
          <li><a href="{% url 'login' %}"><p class="vc-nav-item">Login</p></a></li>
          {% endif %}
        </ul>
      </div>

    </div>
  </div>
</div>

templates/vegancity/partials/privacy_modal.html
{% load url from future %}

    <div id="privacyModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="privacyModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="privacyModalLabel">Privacy Policy</h3>
      </div>
      <div class="modal-body">
        <p>If you have given us your email address and choose to receive updates, we may email you periodically. We will not share your personal information with anyone else. If you have chosen not to receive email updates, we will not contact you unless there is an issue with your account.</p>

        <p>A <a class="uline" target="_blank" href="{% url "privacy" %}">longer version</a> of our privacy policy is also available.</p>
      </div>
    </div>

templates/vegancity/partials/reviews_section.html
{% load url from future %}

{% load vegancity_template_tags %}

<div class="reviews-container">
  <div class="row">
    <div class="span12">

      <div class="reviews-divider">
        {% if show_vendor_name %}
          <img id="left-carrot" src="{{ STATIC_URL }}images/horiz_carrot.png" width="275px">
          <span class="user-review-header"><h2>{{ profile_user }}'s Reviews</h2></span>
          <img id="right-carrot" src="{{ STATIC_URL }}images/horiz_carrot.png" width="275px">
        {% else %}
          <img id="left-carrot" src="{{ STATIC_URL }}images/horiz_carrot.png" width="375px">
          <h2>Reviews</h2>
        <img id="right-carrot" src="{{ STATIC_URL }}images/horiz_carrot.png" width="375px">
        {% endif %}
      </div>
      <br>
      {% if approved_reviews %}
      {% for review in approved_reviews %}

      <div class="reviews-box clearfix">
        {% if show_vendor_name %}
        <div class="reviewed-restaurant"><a href="{{ review.vendor.get_absolute_url }}" target="_blank" rel="nofollow"><h3>{{review.vendor.name }}</h3></a></div>
        {% endif %}
        <span class="review_title"><h3>{{review.title|default:"<em>untitled</em>" }}</h3></span>
        <div class="row clearfix">
            {% if not show_vendor_name %}
            <img class="profile" src="{{ review.author.email|gravatar_urlify }}" title="add your photo on gravatar.com!">
            {% endif %}


          <div class="span5">
            <h4>entered by <a href="{% url 'user_profile' username=review.author.username %}">{{ review.author }}</a> on {{ review.created|date:"M. d, Y" }}</h4>
          </div>
        </div>
        <table class="review_summary">
          {% if review.atmosphere_rating %}
          <tr>
            <td>Atmosphere rating:</td>
            <td class="review_number">{{ review.atmosphere_rating|graphical_rating|safe }}</td>
          </tr>
          {% endif %}
          {% if review.food_rating %}
          <tr>
            <td id="food-rating">Food rating:</td>
            <td class="review_number">{{ review.food_rating|graphical_rating|safe }}</td>
          </tr>
          {% endif %}
          {% if review.best_vegan_dish %}
          <tr>
            <td style="height:42px">Best vegan dish:</td>
            <td class="review_number">{{ review.best_vegan_dish }}</td>
          </tr>
          {% endif %}
        </table>
        <h6>{{ review.content|linebreaks }}</h6>
      </div>
      {% endfor %}

      {% else %}
      <div class="reviews-box">
        <h6>There are no reviews for this vendor yet. Be the first!</h6>
      </div>
      {% endif %}
    </div>
  </div>
</div>

templates/vegancity/partials/vendors_sidebar.html
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Chivo:400,400italic' rel='stylesheet' type='text/css'>

<form action="{% url 'vendors' %}" method="get" name="filters" id="filters" class="form-search">
  <div id="search-area">
    <h4>Search</h4>
    {% if search_from.old_query %}
    <input id="previous_query" name="previous_query" type="hidden" value="{{ previous_query }}">
    {% endif %}
    <input id="search-input" type="text" class="input-large"
           autofocus="autofocus" autocomplete="off" name="current_query"
           {% if current_query %}value="{{ current_query }}"{% endif %}>
    <button class="button search-button" id="search_by_dynamic"><i class="fa fa-caret-right"></i></i></button>
<br>
{% if current_query %}
<h5 id="result-description">
  {% if vendors %}
  Showing only results for "{{ current_query }}"
  {% else %}
  No results for "{{ current_query }}"
  {% endif %}
</h5>
<a href="#" class="button" id="clear_search">Clear Search</a>
{% else %}
{% endif %}
</div>

<div id="filter-area">
  <h4>Browse by Neighborhood</h4>
  <div class="filter-cover">
    <span id="neighborhood_mask"></span>
    <span class="filter-cover-right"><i class="fa fa-caret-down"></i></span>
    <select id="id_neighborhood" name="neighborhood">
      <option value="" {% if not selected_neighborhood_id %}selected="selected"{% endif %}>---------</option>
      {% for neighborhood in neighborhoods %}
      <option value="{{ neighborhood.id }}" {% if neighborhood.id == selected_neighborhood_id %}selected="selected"{% endif %}>{{ neighborhood.name }}</option>
      {% endfor %}
    </select>
  </div>
  <h4>Browse by Cuisine</h4>
  <div class="filter-cover">
    <span id="cuisine_mask"></span>
    <span class="filter-cover-right"><i class="fa fa-caret-down"></i></span>
    <select id="id_cuisine" name="cuisine_tag">
      <option value="" {% if not selected_cuisine_tag_id %}selected="selected"{% endif %}>---------</option>
      {% for cuisine_tag in cuisine_tags %}
      <option value="{{ cuisine_tag.id }}" {% if cuisine_tag.id == selected_cuisine_tag_id %}selected="selected"{% endif %}>{{ cuisine_tag.description }}</option>
      {% endfor %}
    </select>
  </div>

  <h4>Browse by Features</h4>

  <div class="filter-cover features-filter-cover">
    <span class="filter-cover-right"><i class="fa fa-caret-down"></i></span>
    <select id="id_feature" name="feature_tag">
      <option value="" {% if selected_feature_tag %}selected="selected"{% endif %}>---------</option>
      {% for feature_tag in feature_tags %}
      <option value="{{ feature_tag.id }}">
        {{ feature_tag.description }}
      </option>
      {% endfor %}
    </select>
  </div>

  <div id="checked_feature_tags">
    {% for checked in checked_feature_filters %}
    <label class="checkbox">
      <input type="checkbox" id="id_feature_{{ checked.name }}" name="{{ checked.name }}" value="True" checked="checked" onchange="this.form.submit()">
      {{ checked }}
    </label>
    {% endfor %}
  </div>

  {% if selected_neighborhood_id or selected_cuisine_tag_id or checked_feature_filters %}
  <a href="#" class="button" id="clear_all">Clear Filters</a>
  {% else %}
  {% endif %}
</div>
</form>

<div id="vendor-area">
  <h5>Showing {{ vendor_count|default:"0" }} vendors</h5>
  <div class="vendor-filter-cover">Jump to Vendor
    <span class="vendor-filter-cover-right"><i class="fa fa-caret-down"></i></span>
    <select id="id_vendors" name="vendor">
      <option value="">---------</option>
      {% for vendor in vendors %}
      <option value="{{ vendor.id }}">{{ vendor.name }}</option>
      {% endfor %}
    </select>
  </div>
</div>


<div id="add-restaurant-area">
  <h4>Something missing?</h4>
  <a href="{% url 'new_vendor' %}" class="button">Add a Restaurant</a>
</div>

<script>
</script>